name: Release workflow

on:
  push:
    branches:
      - "master"
      - "beta"
      - "next"

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0

      - name: prepare environment
        run: echo SKIPPING
